# documents a stack of services (the one we are building and dependencies of it)
# that we can start to run locally in an isolated and consistent environment
version: '3.2'
services:
  clientweb:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html:ro
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - clientphp
    environment:
      - APP_API_HOST=web
      - APP_LOG_FILE=/application.log

  clientphp:
    hostname: clientphp
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./app/:/app:rw
  db:
    image: mysql/mysql-server
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8182:8080
